# Artificial Neural Network Fundamentals

* ANN: الجوريزم بيحاكي دماغ الانسان بيتعلم من البيانات، زي اللي بيتعلمها الدماغ البشري. بتدريب الشبكة على كمية كبيرة من البيانات، تقدر تتعلم حل مشاكل مختلفة.

# Comparing AI and traditional machine learning

# Learning about the artificial neural network building blocks

# Implementing feedforward propagation

# Calculating the hidden layer unit values

# Applying the activation function

# Calculating the output layer values

# Calculating loss values
* Categorical variable prediction
* Continuous variable prediction

# Feedforward propagation in code

* A high-level strategy of coding feedforward propagation is:

    1. Perform a sum product at each neuron.
    2. Compute activation.
    3. Repeat the first two steps at each neuron until the output layer.
    4. Compute the loss by comparing the prediction with the actual output.

In [3]:
import numpy as np

def sigmoid(dot_value):
    activate_value = 1 / (1 + np.exp(-dot_value)) 
    return activate_value  

def mean_squared_error(pred_value, true_value):
    mse = np.mean(np.square(pred_value - true_value))
    return mse

def feed_forward(inputs,outputs, weights):
    # First hidden layer
    first_hidden_layer = sigmoid(np.dot(inputs, weights[0]) + weights[1])
    
    # Second hidden layer and output layer
    output_layer = sigmoid(np.dot(first_hidden_layer, weights[2]) + weights[3])

    # Calculate the mean squared error
    mean_squared_error_value = mean_squared_error(output_layer,outputs)
    return mean_squared_error_value

# Activation functions in code

In [4]:
def sigmoid(dot_value):
    activate_value = 1 / (1 + np.exp(-dot_value)) 
    return activate_value

def tanh(dot_value):
    activate_value = (np.exp(dot_value)-np.exp(-dot_value))/(np.exp(dot_value)+np.exp(-dot_value))
    return activate_value

def relu(dot_value):
    activate_value =np.where(dot_value>0,dot_value,0)
    return activate_value

def linear(dot_value):
    return dot_value

def softmax(dot_value):
    activate_value = np.exp(dot_value)/np.sum(np.exp(dot_value))
    return activate_value

# Loss functions in code

In [5]:
def mean_squared_error(pred_value, true_value):
    mse = np.mean(np.square(pred_value - true_value))
    return mse

def mean_absolute_error(pred_value, true_value):
    mae = np.mean(np.abs(pred_value - true_value))
    return mae

def binary_cross_entropy(pred_value, true_value):
    bce = -np.mean(true_value*np.log(pred_value)+ (1-true_value)*np.log(1-pred_value))
    return bce

def categorical_cross_entropy(pred_value, true_value):
    cce = -np.mean(np.log(pred_value[np.arange(len(true_value)),true_value]))

# Gradient descent in code

In [12]:
from copy import deepcopy

def update_weights(inputs, outputs, weights, learning_rate):
    
    # Deep copy of the original weights
    original_weights = deepcopy(weights)

    # Create temporary weights for updates
    temp_weights = deepcopy(weights)

    # Create a copy to store the updated weights
    updated_weights = deepcopy(weights)

    # Calculate the original loss
    original_loss = feed_forward(inputs, outputs, original_weights)

    # Loop through layers and weights
    for i, layer in enumerate(original_weights):
        for index, weight in np.ndenumerate(layer):
            
            # Create a deep copy of the weights for this iteration
            temp_weights = deepcopy(weights)
            
            # Add a small perturbation to the weight
            temp_weights[i][index] += 0.0001

            # Calculate the loss with the perturbed weight
            _loss_plus = feed_forward(inputs, outputs, temp_weights)

            # Calculate the gradient
            grad = (_loss_plus - original_loss) / 0.0001

            # Update the weight using gradient descent
            updated_weights[i][index] -= grad * learning_rate

    # Return the updated weights and the original loss
    return updated_weights, original_loss


In [13]:
x = np.array([1, 1])
y = np.array([0])

weights = [
    np.array([[0.8, 0.4, 0.3], [0.2, 0.9, 0.5]]),
    np.array([0.1]),
    np.array([0.3, 0.5, 0.9]),
    np.array([0.3])
]

In [14]:
update_weights(x,y,weights=weights,learning_rate=0.0001)

([array([[0.79999867, 0.39999812, 0.29999563],
         [0.19999867, 0.89999812, 0.49999563]]),
  array([0.09999242]),
  array([0.29998226, 0.49998103, 0.89998319]),
  array([0.29997635])],
 0.6842865333808263)

# Implementing backpropagation using the chain rule

# Putting feedforward propagation and backpropagation together

# Understanding the impact of the learning rate